name: Dependencies check with forcefully
on: [push]

jobs:

    automations:
        name: Dependencies check with forcefully
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies with forcefully
              run: |
                  npm install --force
